version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:@db:3306/power_pulse_gym
      - JWT_SECRET=your_jwt_secret
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME_INBODIES=${S3_BUCKET_NAME_INBODIES}
      - S3_BUCKET_NAME_TRAINEES=${S3_BUCKET_NAME_TRAINEES}
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: power_pulse_gym

    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
