export const AdminWithoutPassword: { [key: string]: boolean } = {
  id: true,
  phoneNumber: true,
  fullName: true,
  gender: true,
  dob: true,
  password: false,
};

export const TraineeWithoutPassword: { [key: string]: boolean } = {
  id: true,
  parcode: true,
  phoneNumber: true,
  fullName: true,
  gender: true,
  dob: true,
  password: false,
  subscriptionType: true,
  subscriptionStatus: true,
  subscriptionDate: true,
  subscriptionStartDate: true,
  subscriptionMonths: true,
  subscriptionClasses: true,
  remainingClasses: true,
  subscriptionEndDate: true,
  paid: true,
  reminder: true,
  trainingName: true,
  offerName: true,
  medicalProblem: true,
  surgeries: true,
  goal: true,
  sundayNote: true,
  mondayNote: true,
  tuesdayNote: true,
  wednesdayNote: true,
  thursdayNote: true,
  fridayNote: true,
  saturdayNote: true,
  generalNote: true,
  idFace: true,
  idBack: true,
};
